services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3001:3001" 
    networks:
      - mern_network
    # environment:
    #   MONGO_URI: mongodb://mongo:27017/mydatabase  
    # depends_on:
    #   - mongodb

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"  
    networks:
      - mern_network
    # environment:
    #   REACT_APP_API_URL: http://backend:3000

  # mongodb:
  #   image: mongo:latest  
  #   ports:
  #     - "27017:27017"  
  #   networks:
  #     - mern_network
  #   volumes:
  #     - mongo-data:/data/db  

networks:
  mern_network:
    driver: bridge 

# volumes:
#   mongo-data:
#     driver: local  # Persist MongoDB data locally
